# Generated by Django 3.2.9 on 2021-11-04 00:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavouritearticle',
            unique_together={('user', 'article')},
        ),
    ]
